"""Add MMM models for Phase 2

Revision ID: c7cb3979e2e6
Revises: 
Create Date: 2025-09-04 16:40:10.481511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7cb3979e2e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ensemble_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_model_ids', sa.JSON(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('ensemble_config', sa.JSON(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('attribution_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ensemble_models_id'), 'ensemble_models', ['id'], unique=False)
    op.create_table('external_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('factor_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('impact_coefficient', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_factors_id'), 'external_factors', ['id'], unique=False)
    op.create_table('marketing_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_data_id'), 'marketing_data', ['id'], unique=False)
    op.create_table('mmm_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model_type', sa.Enum('LIGHTWEIGHT_MMM', 'ROBYN', 'PYMC_MARKETING', 'RIDGE_REGRESSION', name='modeltype'), nullable=False),
    sa.Column('status', sa.Enum('TRAINING', 'COMPLETED', 'FAILED', name='modelstatus'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('training_data_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('training_duration', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mmm_models_id'), 'mmm_models', ['id'], unique=False)
    op.create_table('model_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_ids', sa.JSON(), nullable=True),
    sa.Column('comparison_results', sa.JSON(), nullable=True),
    sa.Column('statistical_significance', sa.JSON(), nullable=True),
    sa.Column('agreement_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_comparisons_id'), 'model_comparisons', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dashboard_mode', sa.String(), nullable=True),
    sa.Column('default_date_range', sa.Integer(), nullable=True),
    sa.Column('preferred_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('model_comparison_models',
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['model_comparisons.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['mmm_models.id'], ),
    sa.PrimaryKeyConstraint('comparison_id', 'model_id')
    )
    op.create_table('model_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('attribution', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('predictions', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('residuals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['mmm_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_results_id'), 'model_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_results_id'), table_name='model_results')
    op.drop_table('model_results')
    op.drop_table('model_comparison_models')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_model_comparisons_id'), table_name='model_comparisons')
    op.drop_table('model_comparisons')
    op.drop_index(op.f('ix_mmm_models_id'), table_name='mmm_models')
    op.drop_table('mmm_models')
    op.drop_index(op.f('ix_marketing_data_id'), table_name='marketing_data')
    op.drop_table('marketing_data')
    op.drop_index(op.f('ix_external_factors_id'), table_name='external_factors')
    op.drop_table('external_factors')
    op.drop_index(op.f('ix_ensemble_models_id'), table_name='ensemble_models')
    op.drop_table('ensemble_models')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
